Below is the modernized version of the function module, converted to an ABAP object-oriented class, ZCL_DTECM, and the SQL query replaced with CDS view ZCDS_DTECM:

CLASS ZCL_DTECM DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES: BEGIN OF T_DOMAIN_FIXED_VALUE,
            DDLANGUAGE TYPE DD07T-DDLANGUAGE,
            VALPOS      TYPE DD07T-VALPOS,
            DOMVALUE_L  TYPE DD07T-DOMVALUE_L,
            DDTEXT      TYPE DD07T-DDTEXT,
           END OF T_DOMAIN_FIXED_VALUE.
    TYPES: TT_DOMAIN_FIXED_VALUE TYPE STANDARD TABLE OF T_DOMAIN_FIXED_VALUE WITH EMPTY KEY.
    
    METHODS CNV_2010C_GET_DOMAIN_FIXED_VAL
      IMPORTING
        !IV_DOMNAME TYPE DOMNAME
      EXPORTING
        !EV_DOMNAME TYPE DOMNAME
      CHANGING
        !CT_DOMAIN_FIXED_VAL TYPE TT_DOMAIN_FIXED_VALUE
        !CS_BAPI_RET TYPE BAPIRET2.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_DTECM IMPLEMENTATION.

  METHOD CNV_2010C_GET_DOMAIN_FIXED_VAL.
    DATA: LS_BAPI_RET TYPE BAPIRET2.

    * Check if iv_domname is empty
    IF IV_DOMNAME IS INITIAL.
      * fill bapiret2
      LS_BAPI_RET-TYPE    = 'E'.
      LS_BAPI_RET-ID      = 'CNV_2010C'.
      LS_BAPI_RET-NUMBER  = '000'.
      LS_BAPI_RET-MESSAGE = 'Text-012'.
      APPEND LS_BAPI_RET TO CS_BAPI_RET.
      RETURN.
    ENDIF.

    * Select data from CDS view ZCDS_DTECM
    SELECT * FROM ZCDS_DTECM
      INTO CORRESPONDING FIELDS OF TABLE CT_DOMAIN_FIXED_VAL
      WHERE DOMNAME   = IV_DOMNAME
        AND DDLANGUAGE = SY-LANGU
        AND AS4LOCAL  = 'A'.

    IF SY-SUBRC = 0.
      SORT CT_DOMAIN_FIXED_VAL ASCENDING BY VALPOS.
      EV_DOMNAME = IV_DOMNAME.
    ELSE.
      * Select data from CDS view ZCDS_DTECM for langu eq EN
      SELECT * FROM ZCDS_DTECM
        INTO CORRESPONDING FIELDS OF TABLE CT_DOMAIN_FIXED_VAL
        WHERE DOMNAME   = IV_DOMNAME
          AND DDLANGUAGE = 'E'
          AND AS4LOCAL  = 'A'.
      IF SY-SUBRC = 0.
        SORT CT_DOMAIN_FIXED_VAL ASCENDING BY VALPOS.
        EV_DOMNAME = IV_DOMNAME.
      ELSE.
        * fill bapiret2
        LS_BAPI_RET-TYPE    = 'E'.
        LS_BAPI_RET-ID      = 'CNV_2010C'.
        LS_BAPI_RET-NUMBER  = '000'.
        LS_BAPI_RET-MESSAGE = 'Text-013'.
        APPEND LS_BAPI_RET TO CS_BAPI_RET.
      ENDIF.
    ENDIF.

  ENDMETHOD.
  
ENDCLASS.